### ISSUE TITLE
[Could be a Bug] Could not get the actual ID from the below code

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/client-net#125]
Hi Team,

I was trying to update a test item using the below code, but I was not able to get the actual ID.
https://github.com/reportportal/client-net/blob/e32d461ec035c79bfcdeca1197ab48f463c0a30a/test/ReportPortal.Client.IntegrationTests/TestItem/UpdateTestItemFixture.cs#L151C15-L151C15

Then I updated the code with 
`await Service.TestItem.UpdateAsync(tempTest.Result.Id, updateRequest);`
instead of 
`await Service.TestItem.UpdateAsync(tempTest.Id, updateRequest);`

Is this change expected? Because the 1st line of code works for me and is updating the test case.

**Comment by nvborisenko** [comment]
@saurabhsrivastava2009 please provide full context of the code you use. The code in examples works for all users, may be you use the library wrong?

**Comment by saurabhsrivastava2009** [comment]
@nvborisenko 
This is the code I'm using
```
string requiredUuid = await Helper.GetUuidForReportPortalItem(_currentTest + _productBuildNumber);

var updateItem = _service.TestItem.GetAsync(requiredUuid);

var updateAsync = _service.TestItem.UpdateAsync(updateItem.Result.Id, new UpdateTestItemRequest
                {
                    Status = status,
                    Attributes = new List<ItemAttribute>()
                    {
                        new ItemAttribute { Key = "testCaseName", Value = testName },
                        new ItemAttribute { Key = "className", Value = onlyClassName },
                        new ItemAttribute { Key = "reRun", Value = "true" }
                    }
                });
TestSetUp.Logger.Log("Update Done for:" + updateItem.Result.Id + " with message:" +
                                     updateAsync.Result.Info);
```

**Comment by nvborisenko** [comment]
And what exactly doesn't work? Any exceptions raised during code execution?

**Comment by saurabhsrivastava2009** [comment]
As per the example given in the repo, we should be using `updateItem.Id`, but this returns single digit number for that run, like 1-N. When I use `updateItem.Result.Id`, i get the actual Uuid.

So the confusion here, which one is correct and `Result.Id` works for me, but you mentioned, only `Id `works too for other users.

**Comment by nvborisenko** [comment]
You don't await async method:
```csharp
var updateItem = _service.TestItem.GetAsync(requiredUuid);
```
