### ISSUE TITLE
Move RetryWithExponentialBackoffHttpClientHandler delegating handler to Shared package

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#29]
This library should not retry http failed requests, it's should be done by Shared library.

**Comment by vitali-sonchyk-epam** [comment]
@nvborisenko , if we move away the initialization of retrier from this library, that how we will initialize it(retrier) for tests in this lib?

**Comment by nvborisenko** [comment]
Upper layers will initialize it. `LaunchReporter` class contains `Service` provided by agents. Agents will use `RetryHandler` by default.

**Comment by vitali-sonchyk-epam** [comment]
@nvborisenko please review pr https://github.com/reportportal/client-net/pull/40
