### ISSUE TITLE
Remove "Newtonsoft.json" dependency

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#3]
Client uses Newtonsoft.json library to serialize/deserialize objects to/from json format. It would be better if Client will use standard/native possibilities to do it without 3rd party libraries.

**Comment by aliaksandrbasau** [comment]
@nvborisenko Do you think it makes sense to implement the same enhancement in agent-net-nunit?
My client updated Newtonsoft.Json in the solution with tests and modified app.config to have bindingRedirect from v9 to v10. But RP integration broke after that. ReportPortal.NUnitExtension is loaded by nunit and nunit app.config has to be updated as well. And it's not so easy to do it on CI server.
