### ISSUE TITLE
Follow client-java and move away from GPL license?

### ISSUE THREAD

**Issue by arevellfraedom** [reportportal/client-net#30]
Currently the license of this client library obligates any consumers of the library to also be released under the GPL license. This isn't acceptable for essentially any commercial company.

Could this client lib have it's license changed, or if not be dual licensed?

I'm hopeful this is possible as this year the java lib made exactly this change:
https://github.com/reportportal/client-java/commit/ec8b7d1a115945cab0d89884dc1c6a5bb97382f1

**Comment by nvborisenko** [comment]
Changed to Apache2.0
