### ISSUE TITLE
Split methods by separate resources according root endpoint

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#32]
Currently we have:
```
service.GetLaunches()
service.StartTestItem()
```

Class `Service` has many methods. It would be better to organize them:
```
service.LaunchResource.GetLaunches()
```

**Comment by vitali-sonchyk-epam** [comment]
So we need to get rid of partial classes?

**Comment by nvborisenko** [comment]
Yes.

**Comment by vitali-sonchyk-epam** [comment]
https://github.com/reportportal/client-net/pull/38
@nvborisenko please review.

**Comment by vitali-sonchyk-epam** [comment]
@nvborisenko , seem like ticket could be closed.

**Comment by nvborisenko** [comment]
It's time to merge changes. New major update is coming.

Actually I'm not sure whether we really need do it right now.
