### ISSUE TITLE
How to send files / pictures to the report portal?

### ISSUE THREAD

**Issue by fasterfish** [reportportal/client-net#4]

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko

**Comment by nvborisenko** [comment]
Example is in Tests project.

https://github.com/reportportal/client-net/blob/master/src/ReportPortal.Client.Tests/LogItem/LogItem.cs

Find `CreateLogWithAttach` test and see code.

```csharp
var data = new byte[] { 1, 2, 3 };
            var log = Service.AddLogItem(new AddLogItemRequest
            {
                TestItemId = _testId,
                Text = "Log1",
                Time = DateTime.UtcNow,
                Level = LogLevel.Info,
                Attach = new Attach("file1", "application/octet-stream", data)
            });
```

**Comment by DzmitryHumianiuk** [comment]
@fasterfish 
i've duplicated it on `stackoverflow` also.
http://stackoverflow.com/questions/41244210/how-can-i-send-files-pictures-to-report-portal-with-net-client
