### ISSUE TITLE
How to use API to get a list of unfinished launches?

### ISSUE THREAD

**Issue by muttonchop** [reportportal/client-net#41]
I am running many tests in parallel and then merging them into a single launch after the fact. How can I use the API to get a list of launches that are unfinished?

**Comment by aliaksandrbasau** [comment]
@muttonchop You can use the following code get all In Progress launches:
```
var launches = await service.GetLaunchesAsync(new FilterOption
{
    Filters = new List<Filter>
    {
        new Filter(FilterOperation.Equals, "status", "IN_PROGRESS")
    }
});
```

To get field names and value that can be used for filtering, I usually go to UI and filter launches through UI, and then inspect network activities:
![image](https://user-images.githubusercontent.com/6681200/59523106-6dd28180-8e9e-11e9-82a3-07dc575846c8.png)

Sometime filters you want to use will be available through UI:
![image](https://user-images.githubusercontent.com/6681200/59523115-775be980-8e9e-11e9-9ddb-6098e4d7a409.png)

**Comment by nvborisenko** [comment]
Thanks @aliaksandrbasau. Considering as resolved.
