### ISSUE TITLE
v5: nested steps: log messages can be tree structured

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#49]

**Comment by mnicula** [comment]
Is there any update on this feature? This would be a really useful feature to have for us)) Thanks in advance

**Comment by nvborisenko** [comment]
@mnicula please try version `3.0.0-beta.1`. You can create nested step as usual test item, but w/ `HasStats=false` property.
```csharp
var nestedStep = await service.TestItem.StartAsync(<parent_test_item>.Uuid, new StartTestItemRequest
            {
                LaunchUuid = <parent_launch>Uuid,
                Name = "This is nestedt step 1",
                HasStats = false,
                StartTime = DateTime.UtcNow
            });
```

Released version might change Client API.

**Comment by nvborisenko** [comment]
@mnicula resolved?

**Comment by mnicula** [comment]
@nvborisenko yes, thanks. It' exactly what I was looking for
