### ISSUE TITLE
nested step status not correctly displayed on UI

### ISSUE THREAD

**Issue by mnicula** [reportportal/client-net#54]
I'm using net-client to log data into rp. When sending FinishAsync request for a NestedStep I expect that in RP the nested step will be marked as failed if it has a log of LogLevel.Fatal in it, but they are always passed unless I provide the Status in the FinishTestItemRequest. Am I doing something wrong?

**Comment by nvborisenko** [comment]
Api trusts you and receives whatever you requests. This is expected behavior.

**Comment by nvborisenko** [comment]
Hoping it's clear. Closing the issue.
