### ISSUE TITLE
Introduce net5.0 as target framework 

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#62]
With
- `System.Text.Json` as serializer

It allows:
- Less memory allocation with better performance

To be carefully tested:
- Shared package is not broken
- Agents, which targets on older framework, can work in cooperation with client/shared targeted to net5.0

Benefits of new json serializer with code gen
![image](https://user-images.githubusercontent.com/22616990/173184285-52531056-e91d-44e3-99c2-e32991f2cad9.png)

Make it possible:
- [x] Find out all usages of Serializer in upstream projects
- [ ] All upstream projects should use own implementation of serializer
  - [ ] NUnit 3
  - [ ] XUnit
  - [ ] VSTest
- [x] Hide serializer here at all

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko, I have investigated usage of `ModelSerializer` class in Report Portal agents and loggers (I've skipped agent usage examples) and what I found:

1. [Common](https://github.com/reportportal/commons-net) - not used.
2. [NUnit3 Agent](https://github.com/reportportal/agent-net-nunit) - used in `LogMessageHandler` class.
3. [NUnit2 Agent](https://github.com/reportportal/agent-net-nunit2) - not used (seems that deprecated).
4. [XUnit Agent](https://github.com/reportportal/agent-net-xunit) - used in `LogHandler` class.
5. [VsTest Agent](https://github.com/reportportal/agent-net-vstest) - used in `LogHandler` class.
6. [SilkTest Agent](https://github.com/reportportal/agent-silktest) - not used.
7. [SpecFlow](https://github.com/reportportal/agent-net-specflow) - not used.
8. [Gauge Agent](https://github.com/reportportal/agent-net-gauge) - not used.
9. [NLog Logger](https://github.com/reportportal/logger-net-nlog) - not used.
10. [Serilog Logger](https://github.com/reportportal/logger-net-serilog) - not used.
11. [Log4Net Logger](https://github.com/reportportal/logger-net-log4net) - not used.
12. [Trace Linstener](https://github.com/reportportal/logger-net-tracelistener) - not used.
