### ISSUE TITLE
Retry amount threshold clarification

### ISSUE THREAD

**Issue by kakosin** [reportportal/client-net#65]
Hello,

Let me first say I've been enjoying the integration of ReportPortal with my NUnit tests. Currently, I've been playing with the retry feature and after reading the doc I found an ambiguous hint as to how the retries are processed: 

> If there were a few invocations of the one test case... (https://reportportal.io/docs/View-launches>retried-test-case-retry-)

Can we clarify how many "few" is please?

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko is the right person to ask

**Comment by nvborisenko** [comment]
Please refer https://github.com/reportportal/agent-net-nunit/issues/56

In summary, agent for NUnit cannot send retried tests to RP.

**Comment by kakosin** [comment]
Hi @nvborisenko , reruns worked for NUnit; I see the rerun icon on my launches.

After some experimenting , I've realized I had one test without `rerun: true` and that's how I've been able to generate different test runs while keeping the rerun feature on those that have the flag on.

**Comment by nvborisenko** [comment]
@kakosin so the issue is not longer actionable?

**Comment by kakosin** [comment]
@nvborisenko , correct. Cool dashboard btw. Sending about 3000-4000 tests on it a day.

**Comment by DzmitryHumianiuk** [comment]
@kakosin we have examples with 180'000 test cases a day in 1 project.
"Sky is the limit" :) (sky=cloud shape size)
