### ISSUE TITLE
Add support of custom defect types

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/client-net#7]
Type property from Issue class has IssueType type (see https://github.com/reportportal/client-net/blob/master/src/ReportPortal.Client/Models/TestItem.cs). As a result, only default defect types (PB001, AB001, etc.) are parsed correctly and Type can't be set to a custom defect type.

**Comment by DzmitryHumianiuk** [comment]
@aliaksandrbasau is it still actual?

**Comment by aliaksandrbasau** [comment]
@DzmitryHumianiuk Yes, it is. IssueType still has enum type with predefined list of values. It's not possible to assign custom defect type (that has a generated value) to enum.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu ^
it's a server side restriction

**Comment by aliaksandrbasau** [comment]
@DzmitryHumianiuk, @avarabyeu No, it's a .NET client issue. I am using the older version of the library where IssueType has string type and can assign customer defect types.

**Comment by DzmitryHumianiuk** [comment]
So it’s for @nvborisenko ?
