### ISSUE TITLE
Include README file in nuget package

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/client-net#72]
https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/

**Comment by Aleh-Yanushkevich** [comment]
I suggest to add the same README file as for GitHub, because of purpose of having this file is the same for both Nuget.org and GitHub. @nvborisenko are you agree?

**Comment by nvborisenko** [comment]
Existing readme would be enough.
