### ISSUE TITLE
FilterOperation values are not the same in requests from Report Portal UI

### ISSUE THREAD

**Issue by Gruuuubik** [reportportal/client-net#92]
# In request from Report Portal UI we have **!has** filter: 

## Example:
/api/v1/{project}/launch?page.page=1&page.size=50&page.sort=startTime%2Cnumber%2CDESC&filter.%21has.compositeAttribute=Android%2CiOS

Report Portal UI version - 5.7.2

# Inside of nuget ReportPortal.Client we have only **has** filter and there are no *!has* filter:

https://github.com/reportportal/client-net/blob/3.0.6/src/ReportPortal.Client/Abstractions/Filtering/Filter.cs#L34

```C#
public enum FilterOperation
{
[DataMember(Name = "eq")] Equals,
[DataMember(Name = "ne")] NotEquals,
[DataMember(Name = "cnt")] Contains,
[DataMember(Name = "!cnt")] NotContains,
[DataMember(Name = "ex")] Exists,
[DataMember(Name = "in")] In,
[DataMember(Name = "!in")] NotIn,
[DataMember(Name = "gt")] GreaterThan,
[DataMember(Name = "gte")] GreaterThanOrEquals,
[DataMember(Name = "lt")] LowerThan,
[DataMember(Name = "lte")] LowerThanOrEquals,
[DataMember(Name = "btw")] Between,
[DataMember(Name = "size")] Size,
[DataMember(Name = "has")] Has,
}
```

ReportPortal.Client version - 3.0.6.
Newer version(3.1.0) has the same FilterOperation enum values.

**Comment by nvborisenko** [comment]
@Aleh-Yanushkevich will you be able to fix it? Seems easy and quick.

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko sure. I'll check if nothing else was added, except `!has`, and fix it.
